/**
 * Copyright (c) 2010-2020 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.openhab.binding.zabbix.internal.api;

/**
 * Exception generated by the Zabbix server during an API call.
 *
 * @author Wilson Waters - Initial addition 20200212
 */
public class ZabbixAPIException extends Exception {

    private static final long serialVersionUID = 1L;

    public ZabbixAPIException() {
        super();
    }

    public ZabbixAPIException(String message) {
        super(message);
    }

    public ZabbixAPIException(String message, Throwable cause) {
        super(message, cause);
    }

    public ZabbixAPIException(Throwable cause) {
        super(cause);
    }

}
